# define a matrix and a function that returns the inverse of this matrix    (3 * 3)

In [1]:
import numpy as np

In [8]:
def dominant_value(matrix):
    eigenvalues, _= np.linalg.eig(matrix)
    dominant_eigenvalue = max(eigenvalues)
    return dominant_eigenvalue

def inverse_matrix(matrix):
    if np.linalg.det(matrix) == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")
    else :
        return np.linalg.inv(matrix)

def identity_matrix(matrix):
    dim = matrix.shape[0]
    return np.identity(dim)

matrix = np.array([[4, 2 , 3], [3, 1, 2] , [5 , 6 , 7]])

dominant_eigenvalue = dominant_value(matrix)
print("Dominant Eigenvalue:", dominant_eigenvalue)

try:
    inverse = inverse_matrix(matrix)
    print("Inverse Matrix:\n", inverse)
except ValueError as e:
    print(e)

identity = identity_matrix(matrix)
print("Identity Matrix:\n", identity)


Dominant Eigenvalue: 11.45326194931462
Inverse Matrix:
 [[ 1.66666667 -1.33333333 -0.33333333]
 [ 3.66666667 -4.33333333 -0.33333333]
 [-4.33333333  4.66666667  0.66666667]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
