# Task 1:

define a matrix and a function that returns the inverse of this matrix    (3 * 3)

In [1]:
import numpy as np

In [8]:
def dominant_value(matrix):
    eigenvalues, _= np.linalg.eig(matrix)
    dominant_eigenvalue = max(eigenvalues)
    return dominant_eigenvalue

def inverse_matrix(matrix):
    if np.linalg.det(matrix) == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")
    else :
        return np.linalg.inv(matrix)

def identity_matrix(matrix):
    dim = matrix.shape[0]
    return np.identity(dim)

matrix = np.array([[4, 2 , 3], [3, 1, 2] , [5 , 6 , 7]])

dominant_eigenvalue = dominant_value(matrix)
print("Dominant Eigenvalue:", dominant_eigenvalue)

try:
    inverse = inverse_matrix(matrix)
    print("Inverse Matrix:\n", inverse)
except ValueError as e:
    print(e)

identity = identity_matrix(matrix)
print("Identity Matrix:\n", identity)

Dominant Eigenvalue: 11.45326194931462
Inverse Matrix:
 [[ 1.66666667 -1.33333333 -0.33333333]
 [ 3.66666667 -4.33333333 -0.33333333]
 [-4.33333333  4.66666667  0.66666667]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Task 2:

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('insurance-data.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

1.2. What is the percentage of female smokers?

In [3]:
total_females = df[df['sex'] == 'female'].shape[0]
female_smokers = df[(df['sex'] == 'female') & (df['smoker'] == 'yes')].shape[0]
percentage_female_smokers = (female_smokers / total_females) * 100
percentage_female_smokers


17.371601208459214

1.3. Which city has the maximum insurance rate?

In [4]:
max_insurance_rate_city = df.groupby('region')['charges'].mean().idxmax()
max_insurance_rate_city

'southeast'

1.4.Which gender has the maximum insurance rate?

In [5]:
max_insurance_rate_gender = df.groupby('sex')['charges'].mean().idxmax()
max_insurance_rate_gender

'male'

1.5. what is the average percentage of female smoker age?

In [6]:
average_female_smoker_age = df[(df['sex'] == 'female') & (df['smoker'] == 'yes')]['age'].mean()
average_female_smoker_age

38.608695652173914

1.6. What is the percentage of males who hase children insurance?


In [7]:
total_males = df[df['sex'] == 'male'].shape[0]
males_with_children = df[(df['sex'] == 'male') & (df['children'] > 0)].shape[0]
percentage_males_with_children_insurance = (males_with_children / total_males) * 100
percentage_males_with_children_insurance

57.84023668639053

1.7. What are the percentage of the females who hase children insurance?

In [8]:
total_females = df[df['sex'] == 'female'].shape[0]
females_with_children = df[(df['sex'] == 'female') & (df['children'] > 0)].shape[0]
percentage_females_with_children_insurance = (females_with_children / total_females) * 100
percentage_females_with_children_insurance

56.34441087613293

1.8. what are the maximum number of children associated with male parent assurance?


In [9]:
max_children_male = df[df['sex'] == 'male']['children'].max()
max_children_male

5

1.9. What are the maximum number of children associated with female parent assurance?

In [11]:
max_children_female = df[df['sex'] == 'female']['children'].max()
max_children_female

5

1.10. Which city has the maximum female insurance total charge?

In [10]:
max_female_insurance_city = df[df['sex'] == 'female'].groupby('region')['charges'].sum().idxmax()
max_female_insurance_city

'southeast'